### ISSUE TITLE
Fails to build debian11/python 3.9: Could NOT find Python (missing: Interpreter Development.Module)

### ISSUE THREAD

**Issue by ovv** [maxbachmann/Levenshtein#52]
Similar to https://github.com/maxbachmann/Levenshtein/issues/39

Investigating the pip install logs it's using the latest scikit-build version 0.17.0

Reproduction:
```
docker run -it debian:bullseye
root@7421095af216:/# apt update
...
root@7421095af216:/# apt install build-essential python3-setuptools python3-pkg-resources python3-all libffi-dev python3-dev python3-venv cmake ninja-build
...
root@7421095af216:/# python3 -V
Python 3.9.2
root@7421095af216:/# python3 -m venv .env
root@7421095af216:/# . .env/bin/activate
(.env) root@7421095af216:/# pip wheel --no-binary=:all: Levenshtein
Collecting Levenshtein
  Downloading Levenshtein-0.20.9.tar.gz (122 kB)
     |████████████████████████████████| 122 kB 4.7 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting rapidfuzz<3.0.0,>=2.3.0
  Downloading rapidfuzz-2.15.1.tar.gz (1.2 MB)
     |████████████████████████████████| 1.2 MB 11.1 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: Levenshtein, rapidfuzz
  Building wheel for Levenshtein (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /.env/bin/python3 /tmp/tmpojm6smub_in_process.py build_wheel /tmp/tmpkzy5d2j7
       cwd: /tmp/pip-wheel-hl85_a02/levenshtein_d1ceb410c7a44bafaa1d765e08b55054
  Complete output (80 lines):
  
  
  --------------------------------------------------------------------------------
  -- Trying 'Ninja' generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 10.2.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 10.2.1
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-wheel-hl85_a02/levenshtein_d1ceb410c7a44bafaa1d765e08b55054/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying 'Ninja' generator - success
  --------------------------------------------------------------------------------
  
  Configuring Project
    Working directory:
      /tmp/pip-wheel-hl85_a02/levenshtein_d1ceb410c7a44bafaa1d765e08b55054/_skbuild/linux-x86_64-3.9/cmake-build
    Command:
      /usr/bin/cmake /tmp/pip-wheel-hl85_a02/levenshtein_d1ceb410c7a44bafaa1d765e08b55054 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-wheel-hl85_a02/levenshtein_d1ceb410c7a44bafaa1d765e08b55054/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.2 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-a94e4xto/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/.env/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.9 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.9.so -DPython_EXECUTABLE:PATH=/.env/bin/python3 -DPython_ROOT_DIR:PATH=/.env -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/include/python3.9 -DPython_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.9.so -DPython3_EXECUTABLE:PATH=/.env/bin/python3 -DPython3_ROOT_DIR:PATH=/.env -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.9 -DPython3_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.9.so -DCMAKE_BUILD_TYPE:STRING=Release
  
  -- The C compiler identification is GNU 10.2.1
  -- The CXX compiler identification is GNU 10.2.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
    Could NOT find Python (missing: Interpreter Development.Module)
  Call Stack (most recent call first):
    /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
    /usr/share/cmake-3.18/Modules/FindPython.cmake:436 (find_package_handle_standard_args)
    CMakeLists.txt:25 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-wheel-hl85_a02/levenshtein_d1ceb410c7a44bafaa1d765e08b55054/_skbuild/linux-x86_64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "/tmp/pip-build-env-a94e4xto/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 662, in setup
      env = cmkr.configure(
    File "/tmp/pip-build-env-a94e4xto/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 355, in configure
      raise SKBuildError(msg)
  
  An error occurred while configuring with CMake.
    Command:
      {self._formatArgsForDisplay(cmd)}
    Source directory:
      {os.path.abspath(cmake_source_dir)}
    Working directory:
      {os.path.abspath(CMAKE_BUILD_DIR())}
  Please see CMake's output for more information.
  
  ----------------------------------------
  ERROR: Failed building wheel for Levenshtein
  Building wheel for rapidfuzz (PEP 517) ... done
  Created wheel for rapidfuzz: filename=rapidfuzz-2.15.1-py3-none-any.whl size=67496 sha256=f833a73e3d02842a1086f5245acc72eb7ec24803e43f96f53abb5925ea8cac84
  Stored in directory: /root/.cache/pip/wheels/61/f6/0c/6f43121b33df553ca9e9fabcd158500dec591cc08c6c933a39
Successfully built rapidfuzz
Failed to build Levenshtein
ERROR: Failed to build one or more wheels
```

**Comment by maxbachmann** [comment]
@henryiii this sounds like a bug in scikit-build. Following #39 it appears I at least thought this was fixed in scikit-build. Since https://github.com/scikit-build/scikit-build/issues/718 is still open it is possible this was never actually fixed.

**Comment by maxbachmann** [comment]
When building rapidfuzz from source, it falls back to a Python only version if the compilation fails. So I assume it failed as well and just installed the fallback version instead.

**Comment by henryiii** [comment]
Ahh, okay. Unrelated, we can improve that error message too. 🤦

**Comment by maxbachmann** [comment]
Yes fails for rapidfuzz as well:
```
RAPIDFUZZ_BUILD_EXTENSION=1 pip install --no-binary=rapidfuzz rapidfuzz
```
fails with the same error message

**Comment by henryiii** [comment]
Does this happen with 0.16.x?

**Comment by maxbachmann** [comment]
This appears to be related to this in my cmake files:
```
if(CMAKE_VERSION VERSION_LESS 3.18)
  find_package(
    Python
    COMPONENTS Interpreter Development
    REQUIRED)
else()
  set(Python_ARTIFACTS_INTERACTIVE TRUE)
  find_package(
    Python
    COMPONENTS Interpreter Development.Module
    REQUIRED)
endif()
```

on debian11 I have cmake 3.18.4, so it uses `Development.Module` instead of `Development`. If I change this so it uses `Development` (https://github.com/maxbachmann/RapidFuzz/commit/9f594c8ca8d521bbff5aebf33a8dc5502ba9241c) it builds fine.

**Comment by maxbachmann** [comment]
> Does this happen with 0.16.x?

No this issue appears to be new in 0.17.0

**Comment by maxbachmann** [comment]
Looking at the cmake commandline the only difference appears to be:
```
 -DPython_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.9.so -DPython3_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.9.so 
```
So those might be the problems you talked about in https://github.com/scikit-build/scikit-build/pull/913

**Comment by maxbachmann** [comment]
In my experiments cmake 3.24.0 is the first version this does not fail on.

**Comment by henryiii** [comment]
Scikit-build-core should handle this correctly, then, as it backports FindPython from 3.26.1. Yes, that's probably it. So it was fixed in the rewrite with 3.24.

This is not really needed except on Windows, so maybe we could disable it for CMake < 3.24 not running on Windows?

**Comment by maxbachmann** [comment]
> Scikit-build-core should handle this correctly, then, as it backports FindPython from 3.26.1. Yes, that's probably it. So it was fixed in the rewrite with 3.24.

Is there any way to implement my fallback behavior from https://github.com/maxbachmann/RapidFuzz/blob/patch3/setup.py using scikit-build-core yet? I think this is the only thing stopping me from switching to it.

> This is not really needed except on Windows, so maybe we could disable it for CMake < 3.24 not running on Windows?

Sounds good to me

**Comment by maxbachmann** [comment]
@ovv can you retry with `scikit-build==0.17.1`? This should fix the issue.

**Comment by ovv** [comment]
I confirm it's working now. Thanks for the quick fix.
